# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SW_Mini_Project_v1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SW_Mini_Project_v1
pod 'GoogleSignIn'
pod 'Firebase/Core'
pod 'Firebase/Database'

end
